version: '3'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-rekam-medis
        container_name: laravel-rekam-medis
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker-config/nginx.conf:/etc/nginx/nginx.conf
            - ./docker-config/php.ini:/etc/php7/conf.d/custom.ini
        networks:
            # - docker_main
            - mainapp
        ports:
            - 8083:8080

    npm:
        image: node:17-alpine
        container_name: npm-rekam-medis
        restart: unless-stopped
        working_dir: /var/www/html
        entrypoint: ["npm"]
        depends_on:
        - app
        volumes:
        - ./:/var/www/html
            
# networks:
#     docker_main:
#         name: docker_main

networks:
    mainapp:
        name: mainapp