version: '3'

services:
    app:
        deploy:
         resources:
          limits:
           memory: 512M
        build:
            args:
             uid: ${DOCKER_UID}
             gid: ${DOCKER_GID}
            context: ./
            dockerfile: Dockerfile
        image: laravel-rekam-medis
        container_name: laravel-rekam-medis
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker-config/nginx.conf:/etc/nginx/nginx.conf
            - ./docker-config/php.ini:/etc/php7/conf.d/custom.ini
        networks:
            # - docker_main
            - mainapp
        ports:
            - 8083:8080
            
networks:
     docker_main:
         name: docker_main

#networks:
#    mainapp:
#        name: mainapp
